# Generated by Django 3.2.6 on 2024-07-04 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SongRank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.IntegerField()),
                ('song', models.CharField(max_length=255)),
                ('streams', models.CharField(max_length=5)),
                ('artist', models.CharField(max_length=500)),
                ('release_date', models.DateField(null=True)),
            ],
        ),
    ]
